version: '2'
services:
  chrome:
    image: yukinying/chrome-headless
    restart: always
    mem_limit: 1g
    cpuset: '1'
  renderer:
    image: pandamako/renderer
    restart: always
    mem_limit: 100m
    environment:
      CHROME_HOST: chrome
    ports:
      - 8887:8000
    depends_on:
      - chrome
